### ISSUE TITLE
Don't modify XML header

### ISSUE THREAD

**Issue by johnwason** [efrecon/pre-commit-hook-lxml#15]
The XML header is being modified by this formatter. For example, `<?xml version="1.0"?>` is being modified to `<?xml version='1.0' encoding='UTF-8'?>`. The header shouldn't be modified by this tool.

**Comment by efrecon** [comment]
I agree that it shouldn't modify the declaration (unless to an equivalent perhaps). I've double check the manual for the underlying library, and the current call to [tostring](https://lxml.de/api/lxml.etree-module.html#tostring) uses the encoding reported by the XML parser as a [DocInfo](https://lxml.de/api/lxml.etree.DocInfo-class.html). Any kind of guideline as to what the correct behaviour should be provided the current API? This hook is merely a call to `XML()` and then `tostring()` to reformat.

Could it be that your file has a [BOM](https://www.liquid-technologies.com/Reference/Glossary/XML_Encoding.html), in which case UTF-8 will be inferred from the presence of the BOM?

**Comment by efrecon** [comment]
Lacking any further input, I am closing this. ff1f4e859396e44b5f9963bf145a5ab6fc032ae9 provides partial effort into the requested direction.
