### ISSUE TITLE
Add option to preserve blank lines

### ISSUE THREAD

**Issue by johnwason** [efrecon/pre-commit-hook-lxml#16]
We sometimes use blank lines to organize the contents of the XML file. It would be helpful if there was an option to preserve blank lines.

**Comment by efrecon** [comment]
We faced the same problem and just accepted that standardized formatting of XML files was more important than keeping blank lines. The underlying library [tostring](https://lxml.de/api/lxml.etree-module.html#tostring) method is not able to preserve blank lines, to what I can understand.

Nodes seems to have line information attached to them, but using this information to "pretty-print" would require to rewrite the `tostring` method inside the hook. This falls a little outside of the scope of this implementation.

**Comment by efrecon** [comment]
You are welcome to send a PR to fix this, but in the mean time I will close this.
